services:
  redis:
    container_name: redis
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - my-network
  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    ports:
      - "8001:8001"
    expose:
      - "8001"
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
